import nodemailer from 'nodemailer';

const sendEmail = async (options) => {
  const transporter = nodemailer.createTransport({
    service: process.env.EMAIL_SERVICE,
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });

  try {
    // More visually appealing HTML template for developer notification
    const developerHtmlTemplate = `
      <body style="background-color: #f4f4f4; margin: 0; padding: 0; font-family: 'Arial', sans-serif;">
        <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%">
          <tr>
            <td align="center" style="padding: 20px;">
              <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="600" style="border-radius: 8px; overflow: hidden;">
                <tr>
                  <td bgcolor="#5cb85c" style="padding: 40px 30px 30px 30px; text-align: center;">
                    <h2 style="color: #ffffff; font-size: 24px; margin-top: 0;">Hire Me Request</h2>
                  </td>
                </tr>
                <tr>
                  <td bgcolor="#ffffff" style="padding: 30px 30px 30px 30px;">
                    <h3 style="color: #333333; font-size: 18px; margin-top: 0;">Details:</h3>
                    <p style="color: #555555; font-size: 16px; line-height: 1.6;">
                      <strong style="color: #555555;">Name:</strong> ${options.name || 'N/A'}<br>
                      <strong style="color: #555555;">Email:</strong> ${options.email || 'N/A'}<br>
                      <strong style="color: #555555;">Subject:</strong> ${options.subject || 'N/A'}<br>
                      <strong style="color: #555555;">Project:</strong> ${options.project || 'N/A'}<br>
                      <strong style="color: #555555;">Price Range:</strong> ${options.priceRange || 'N/A'}<br>
                    </p>
                    <p style="color: #555555; font-size: 16px;"><strong>Message:</strong></p>
                    <p style="color: #555555; font-size: 16px; line-height: 1.6; white-space: pre-wrap;">${options.text || 'N/A'}</p>
                    <hr style="margin-top: 30px; border: 1px solid #f0f0f0;">
                    <p style="color: #777777; font-size: 12px; text-align: center; margin-top: 20px;">
                      This email was sent from the contact form on RIFAT the DEV.
                    </p>
                  </td>
                </tr>
                <tr>
                  <td bgcolor="#f4f4f4" style="padding: 15px 30px 15px 30px; font-size: 12px; color: #777777; text-align: center; border-radius: 0 0 8px 8px;">
                    Generated by RIFAT the DEV's contact form.
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
      </body>
    `;

    const mailOptions = {
      from: process.env.EMAIL_USER,
      to: 'alrifat2004@gmail.com',
      subject: `New Contact Form Submission: ${options.subject || 'No Subject'}`,
      html: developerHtmlTemplate,
    };

    await transporter.sendMail(mailOptions);
     console.log('Email sent successfully to developer');
  } catch (error) {
    console.error('Error sending email to developer:', error);
    throw error;
  }
};

const sendConfirmationEmail = async (options) => {
  const transporter = nodemailer.createTransport({
    service: process.env.EMAIL_SERVICE,
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });

  try{
    // More visually appealing HTML template for user confirmation
    const userHtmlTemplate = `
      <body style="background-color: #f4f4f4; margin: 0; padding: 0; font-family: 'Arial', sans-serif;">
          <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%">
            <tr>
              <td align="center" style="padding: 20px;">
                <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="600" style="border-radius: 8px; overflow: hidden;">
                  <tr>
                    <td bgcolor="#285E63" style="padding: 40px 30px 30px 30px; text-align: center;">
                      <a href="#" target="_blank" rel="noopener noreferrer" style="text-decoration: none;">
                        <img src="https://res.cloudinary.com/dtspm3365/image/upload/v1746116818/logo2_gg0zrp.png" alt="RIFAT the DEV." width="200" style="display: block; margin-left: 33%;">
                        <h1 style="color: #ffffff; font-size: 24px; transform: translateY(-100%);">RIFAT the DEV.</h1>
                      </a>
                    </td>
                  </tr>
                  <tr>
                    <td bgcolor="#ffffff" style="padding: 30px 30px 30px 30px;">
                      <h2 style="color: #333333; font-size: 20px; margin-top: 0;">Hey, ${options.name}</h2>
                      <p style="color: #555555; font-size: 16px; line-height: 1.6;">
                          Thank you for reaching out with your kind request to engage my services for ${options.project} and for providing 
                          the initial price range. I have reviewed your submission with interest. To ensure a clear understanding of the project's 
                          intricacies and to ascertain the best way I can assist you, I would appreciate the opportunity to schedule a brief discussion 
                          at your earliest convenience. Please let me know what time might suit you best.
                      </p>
                      <p style="color: #555555; font-size: 16px; margin-top: 20px;">
                        Best regards,<br>
                        RIFAT the DEV.
                      </p>
                    </td>
                  </tr>
                  <tr>
                    <td bgcolor="#f4f4f4" style="padding: 20px 30px 20px 30px; font-size: 12px; color: #777777; text-align: center;">
                      <h3 style="color: #777777; margin-top: 0;">Connect with me:</h3>
                      <p style="margin-bottom: 10px;">
                        <a href="https://github.com/alrifatsabbir" target="_blank" rel="noopener noreferrer" style="color: #285E63; text-decoration: none; margin: 0 10px;">GitHub</a>
                        <a href="https://www.linkedin.com/in/alrifatsabbir/" target="_blank" rel="noopener noreferrer" style="color: #285E63; text-decoration: none; margin: 0 10px;">LinkedIn</a>
                        <a href="https://wa.me/+8801688525596" target="_blank" rel="noopener noreferrer" style="color: #285E63; text-decoration: none; margin: 0 10px;">WhatsApp</a>
                        <a href="https://m.me/Al.Rifat.Sabbir" target="_blank" rel="noopener noreferrer" style="color: #285E63; text-decoration: none; margin: 0 10px;">Messenger</a>
                        <a href="https://twitter.com/alrifatsabbir" target="_blank" rel="noopener noreferrer" style="color: #285E63; text-decoration: none; margin: 0 10px;">Twitter</a>
                        <a href="https://www.youtube.com/@codearcglobal" target="_blank" rel="noopener noreferrer" style="color: #285E63; text-decoration: none; margin: 0 10px;">YouTube</a>
                        <a href="https://www.facebook.com/al.rifat.sabbir47/" target="_blank" rel="noopener noreferrer" style="color: #285E63; text-decoration: none; margin: 0 10px;">Facebook</a>
                        <a href="https://www.instagram.com/alrifatsabbir" target="_blank" rel="noopener noreferrer" style="color: #285E63; text-decoration: none; margin: 0 10px;">Instagram</a>
                      </p>
                      <p style="margin-top: 20px;">
                        Phone: <a href="tel:+8801688525596" style="color: #285E63; text-decoration: none;">+880-1688-525596</a>
                      </p>
                    </td>
                  </tr>
                  <tr>
                    <td bgcolor="#e0e0e0" style="padding: 15px 30px 15px 30px; font-size: 12px; color: #777777; text-align: center; border-radius: 0 0 8px 8px;">
                      © ALL RIGHTS RESERVED BY alrifatsabbir || RIFAT the DEV.
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
        </body>  `;

    const mailOptions = {
      from: process.env.EMAIL_USER,
      to: options.to,
      subject: 'Confirmation: Your inquiry has been received',
      html: userHtmlTemplate,
      text: `Thank you for contacting us. We have received your message and will respond as soon as possible.`,
    };

    await transporter.sendMail(mailOptions);
    console.log('Confirmation email sent successfully to user');
  } catch (error) {
     console.error('Error sending confirmation email to user:', error);
    throw error;
  }
};

export { sendEmail, sendConfirmationEmail };